
###################### Sample info ######################

SAMPLE:
  Treated_rep1: SRR6461133
  Treated_rep2: SRR6461134
  Treated_rep3: SRR6461135
  Control_rep1: SRR6461139
  Control_rep2: SRR6461140
  Control_rep3: SRR6461141



END: 
  - 1
  - 2


